#!/system/bin/sh
# pulser@xda-developers.com
# Changes the DPI of CM, persisting through nightly installs
# Changes from 320 dpi to 240 dpi

if grep -Fxq "ro.sf.lcd_density=320" /system/build.prop 
then 
    mount -o remount,rw /system
    sed s/ro.sf.lcd_density=320/ro.sf.lcd_density=240/ < /system/build.prop > /system/build.prop.new
    mv /system/build.prop.new /system/build.prop
    mount -o remount,ro /system
    reboot
fi
